config/routes.rb
Rails.application.routes.draw do
  # get 'todo/index'
  # get "/todo", to: "todo#index"
  # get "/todo/:id", to: "todo#show"
 

  resources :todo
  root "todo#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  validates :todo, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to @todo
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update(todo_params)
      redirect_to todo_index_path, notice: 'Todo was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def todo_params
    params.require(:todo).permit(:title, :todo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo/_form.html.erb
  <div class="d-flex justify-content-end">
    <%= link_to "Back", todo_index_path, "class": "btn btn-info" %>
  </div>
  <%= form_with model: @todo, url: @todo.persisted? ? todo_path(@todo) : todo_index_path do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
      <% @todo.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="form-group my-4">
      <%= form.label :todo %>
      <%= form.text_area :todo, class: 'form-control' %>
      <% @todo.errors.full_messages_for(:todo).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.submit 'Submit', class: 'btn btn-primary' %>
    </div>
  <% end %>

app/views/todo/edit.html.erb
<section class="container my-5">
  <h1 class="">Edit Todo</h1>
  <%= render "form", todo: @todo %>
</section>

app/views/todo/index.html.erb
<section class="container my-5">
  <h1>My Todos</h1>
  <div class="d-flex justify-content-end">
    <%= link_to "Add todo", new_todo_path, "class": "btn btn-info" %>
  </div>
  <table class="table my-3">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Todo</th>
        <th scope="col">Created Time</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
    <% @todos.each_with_index do |todo,index| %>
      <tr>
        <td><%= index+1 %></td>
        <td>
          <%= link_to todo.title, todo %>
        </td>
        <td><%= todo.todo %></td>
        <td><%= todo.created_at ? todo.created_at.strftime("%Y-%m-%d %H:%M") : "N/A" %></td>
        <td>
        <%= link_to "Edit", edit_todo_path(todo) , "class": "btn btn-info" %>
        <%= 
          link_to "Destroy", 
          todo_path(todo), 
          "class": "btn btn-danger",
          data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                }
        %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/todo/new.html.erb
<section class="container my-5">
  <h1 class="">New Todo</h1>
  <%= render "form", todo: @todo %>
</section>

app/views/todo/show.html.erb
<section class="d-flex flex-column justify-content-center align-items-center min-vh-100 py-5">
  <div class="card bg-light mb-3 w-100" style="max-width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= @todo.title %></h5>
      <p class="card-text"><%= @todo.todo %></p>
    </div>
  </div>
  <div>
    <%= link_to "Back", todo_index_path, "class": "btn btn-info" %>
    <%= link_to "Edit", edit_todo_path(@todo), "class": "btn btn-secondary" %>
    <%= 
      link_to "Destroy", 
      todo_path(@todo), 
      "class": "btn btn-danger",
      data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            }
    %>
  </div>
</section>